SELECT
  SHOP_MONTH,
  NEW_STATUS,
  REPEAT_STATUS,
  REACTIVE_STATUS,
  TOTAL,
  LAG(TOTAL, 1)OVER(ORDER BY SHOP_MONTH ASC) AS PREVIOUS_TOTAL,
  REPEAT_STATUS - LAG(TOTAL, 1)OVER(ORDER BY SHOP_MONTH ASC) AS CHURN_STATUS
FROM (
  SELECT
    SHOP_MONTH,
    COUNT(CASE
        WHEN STATUS = 'NEW' THEN CUST_CODE
      ELSE
      NULL
    END
      ) AS NEW_STATUS,
    COUNT(CASE
        WHEN STATUS = 'REPEAT' THEN CUST_CODE
      ELSE
      NULL
    END
      ) AS REPEAT_STATUS,
    COUNT(CASE
        WHEN STATUS = 'REACTIVE' THEN CUST_CODE
      ELSE
      NULL
    END
      ) AS REACTIVE_STATUS,
    COUNT(STATUS) AS TOTAL
  FROM (
    SELECT
      PREVIOUS_MONTH,
      SHOP_MONTH,
      CUST_CODE,
      CASE
        WHEN DATE_DIFF(SHOP_MONTH, PREVIOUS_MONTH, MONTH) IS NULL THEN 'NEW'
        WHEN DATE_DIFF(SHOP_MONTH, PREVIOUS_MONTH, MONTH) = 1 THEN 'REPEAT'
        WHEN DATE_DIFF(SHOP_MONTH, PREVIOUS_MONTH, MONTH) > 1 THEN 'REACTIVE'
      ELSE
      NULL
    END
      AS STATUS
    FROM (
      SELECT
        LAG(SHOP_MONTH, 1)OVER(PARTITION BY CUST_CODE ORDER BY SHOP_MONTH ASC) AS PREVIOUS_MONTH,
        SHOP_MONTH,
        CUST_CODE
      FROM (
        SELECT
          DISTINCT DATE_TRUNC(PARSE_DATE('%Y%m%d',
              CAST(SHOP_DATE AS STRING)),MONTH) AS SHOP_MONTH,
          CUST_CODE
        FROM
          `bads7105-cs.supermarket.supermarket_`
        WHERE
          CUST_CODE IS NOT NULL ) ) )
  GROUP BY
    SHOP_MONTH )
ORDER BY
  SHOP_MONTH